"use client";
import { useEffect,useState } from "react";import Link from "next/link";import { authApi,formatRwf } from "../../lib/api";
export default function Dashboard(){
 const[data,setData]=useState<any>();const[props,setProps]=useState<any[]>([]);const[bookings,setBookings]=useState<any[]>([]);const[err,setErr]=useState("");
 useEffect(()=>{Promise.all([authApi<any>("/analytics/landlord"),authApi<any[]>("/properties/owned"),authApi<any[]>("/bookings")]).then(([a,p,b])=>{setData(a);setProps(p||[]);setBookings(b||[])}).catch(e=>setErr(e.message))},[]);
 return <main className="wrap section"><div className="sectionHead"><div><div className="eyebrow">Owner workspace</div><h1>Good to see you.</h1><p className="muted">Your live portfolio, activity and transaction performance.</p></div><div className="actions"><Link className="btn" href="/manage">＋ New listing</Link><Link className="btn ghost" href="/notifications">Notifications</Link></div></div>
 {err&&<div className="notice error" style={{marginTop:18}}>{err} · <Link href="/login">Sign in</Link></div>}
 {data&&<div className="stats" style={{marginTop:24}}>{[["Properties",data.properties],["Active",data.active],["Views",data.views],["Bookings",data.bookings],["Revenue",formatRwf(data.revenue||0)]].map(([label,value])=><div className="stat" key={String(label)}><span className="muted">{label}</span><b>{value}</b><span className="delta">Live backend metric</span></div>)}</div>}
 <section className="section"><div className="sectionHead"><div><div className="eyebrow">Portfolio</div><h2>Your properties</h2></div><Link href="/manage" className="muted">Open manager →</Link></div><div className="list">{props.slice(0,8).map(p=><Link className="row" href={"/properties/"+p.id} key={p.id}><span><b>{p.title}</b><br/><small className="muted">{p.district} · {p.status}</small></span><span className="pill">{p.verificationStatus||"Listed"}</span></Link>)}</div>{!props.length&&<div className="empty"><h3>Your portfolio is empty</h3><p>Create a property and listing to start operating inventory.</p><Link className="btn" href="/manage">Create property</Link></div>}</section>
 <section className="section"><div className="sectionHead"><div><div className="eyebrow">Operations</div><h2>Recent bookings</h2></div><Link href="/bookings" className="muted">View all →</Link></div><div className="list">{bookings.slice(0,8).map(b=><div className="row" key={b.id}><span><b>Booking {String(b.id).slice(0,8)}…</b><br/><small className="muted">{b.startDate} → {b.endDate}</small></span><span className="pill">{b.status}</span></div>)}</div>{!bookings.length&&<div className="empty">No bookings returned by the API.</div>}</section>
 </main>;
}