import{router}from"expo-router";import{useEffect,useState}from"react";import{Modal,FlatList,Pressable,ScrollView,StyleSheet,Text,TextInput,View}from"react-native";import{api}from"../src/lib/api";
type Item={id:string;name:string;code:string};
const levels=[["provinceId","province","PROVINCE"],["districtId","district","DISTRICT"],["sectorId","sector","SECTOR"],["cellId","cell","CELL"],["villageId","village","VILLAGE"]] as const;
function Select({label,items,value,onChange,disabled}:{label:string;items:Item[];value:string;onChange:(id:string)=>void;disabled?:boolean}){
 const[itemOpen,setOpen]=useState(false);const[q,setQ]=useState("");const selected=items.find(x=>x.id===value);
 return <><Pressable style={[s.select,disabled&&{opacity:.45}]} disabled={disabled} onPress={()=>setOpen(true)}><Text style={selected?s.value:s.placeholder}>{selected?.name||"Select "+label}</Text><Text>⌄</Text></Pressable><Modal visible={itemOpen} transparent animationType="slide" onRequestClose={()=>setOpen(false)}><View style={s.modal}><View style={s.sheet}><Text style={s.h2}>Select {label}</Text><TextInput style={s.input} placeholder={"Search "+label} value={q} onChangeText={setQ}/><FlatList data={items.filter(x=>x.name.toLowerCase().includes(q.toLowerCase()))} keyExtractor={x=>x.id} renderItem={({item})=><Pressable style={s.option} onPress={()=>{onChange(item.id);setOpen(false);setQ("")}}><Text style={{fontWeight:"700"}}>{item.name}</Text><Text style={s.muted}>{item.code}</Text></Pressable>}/><Pressable style={s.close} onPress={()=>setOpen(false)}><Text>Close</Text></Pressable></View></View></Modal></>
}
export default function AddProperty(){
 const[f,setF]=useState<any>({title:"",description:"",propertyType:"HOUSE",listingType:"RENT",priceMinor:"",currency:"RWF",provinceId:"",districtId:"",sectorId:"",cellId:"",villageId:"",province:"",district:"",sector:"",cell:"",village:"",latitude:"-1.95",longitude:"30.06",bedrooms:"3",bathrooms:"2",parking:"1"});
 const[o,setO]=useState<Record<string,Item[]>>({PROVINCE:[],DISTRICT:[],SECTOR:[],CELL:[],VILLAGE:[]});const[busy,setBusy]=useState(false);const[err,setErr]=useState("");
 useEffect(()=>{void load("PROVINCE");},[]);
 async function load(level:string,parentId?:string){try{const p=parentId?`?level=${level}&parentId=${parentId}`:`?level=${level}`;const rows=await api<Item[]>(`/locations/rwanda${p}`,{},false);setO(x=>({...x,[level]:rows}));}catch(e:any){setErr(e.message)}}
 function choose(key:string,name:string,level:string,id:string){const reset:any={provinceId:"",districtId:"",sectorId:"",cellId:"",villageId:"",province:"",district:"",sector:"",cell:"",village:""};const idx=levels.findIndex(x=>x[0]===key);const next:any={...f,[key]:id,[name]:o[level].find(x=>x.id===id)?.name||""};for(let i=idx+1;i<levels.length;i++){next[levels[i][0]]="";next[levels[i][1]]=""}setF(next);if(level!=="VILLAGE")void load(levels[idx+1][2],id)}
 async function submit(){setBusy(true);setErr("");try{const p=await api<any>("/properties",{method:"POST",body:JSON.stringify({...f,latitude:Number(f.latitude),longitude:Number(f.longitude),bedrooms:Number(f.bedrooms),bathrooms:Number(f.bathrooms),parking:Number(f.parking),priceMinor:undefined,listingType:undefined})},true);await api("/listings",{method:"POST",body:JSON.stringify({propertyId:p.id,listingType:f.listingType,priceMinor:Number(f.priceMinor),currency:f.currency,availableFrom:new Date().toISOString()})},true);router.replace("/property/"+p.id)}catch(e:any){setErr(e.message)}finally{setBusy(false)}}
 return <ScrollView style={s.root} contentContainerStyle={s.pad}><Pressable onPress={()=>router.back()}><Text>← Back</Text></Pressable><Text style={s.eyebrow}>LIST PROPERTY</Text><Text style={s.h1}>Add a house</Text><Text style={s.lead}>Choose the exact Rwanda administrative location. The backend validates every parent-child relationship.</Text>{err&&<Text style={s.error}>{err}</Text>}<Text style={s.h2}>Property</Text><TextInput style={s.input} placeholder="House title" value={f.title} onChangeText={v=>setF({...f,title:v})}/><TextInput style={[s.input,s.area]} multiline placeholder="Description" value={f.description} onChangeText={v=>setF({...f,description:v})}/><TextInput style={s.input} placeholder="Property type" value={f.propertyType} onChangeText={v=>setF({...f,propertyType:v.toUpperCase()})}/><Text style={s.h2}>Rwanda location</Text>{levels.map(([key,name,level],i)=><Select key={key} label={name} items={o[level]} value={f[key]} disabled={i>0&&!f[levels[i-1][0]]} onChange={id=>choose(key,name,level,id)}/>)}<View style={s.row}><TextInput style={s.half} keyboardType="numeric" placeholder="Latitude" value={f.latitude} onChangeText={v=>setF({...f,latitude:v})}/><TextInput style={s.half} keyboardType="numeric" placeholder="Longitude" value={f.longitude} onChangeText={v=>setF({...f,longitude:v})}/></View><View style={s.row}><TextInput style={s.half} keyboardType="numeric" placeholder="Bedrooms" value={f.bedrooms} onChangeText={v=>setF({...f,bedrooms:v})}/><TextInput style={s.half} keyboardType="numeric" placeholder="Bathrooms" value={f.bathrooms} onChangeText={v=>setF({...f,bathrooms:v})}/></View><Text style={s.h2}>Rent or sale</Text><View style={s.row}>{["RENT","SALE"].map(x=><Pressable key={x} style={[s.choice,f.listingType===x&&s.choiceActive]} onPress={()=>setF({...f,listingType:x})}><Text style={f.listingType===x?s.choiceTextActive:s.choiceText}>{x}</Text></Pressable>)}</View><TextInput style={s.input} keyboardType="numeric" placeholder="Price (RWF)" value={f.priceMinor} onChangeText={v=>setF({...f,priceMinor:v})}/><Pressable style={s.button} disabled={busy} onPress={()=>void submit()}><Text style={s.buttonText}>{busy?"Saving…":"Create property and listing →"}</Text></Pressable></ScrollView>
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:"#F5F7F9"},pad:{padding:18,paddingBottom:80},eyebrow:{fontSize:11,fontWeight:"900",letterSpacing:2,color:"#0F5132",marginTop:22},h1:{fontSize:34,fontWeight:"900",marginTop:7,color:"#0B1220"},h2:{fontSize:20,fontWeight:"900",marginTop:22,marginBottom:9},lead:{color:"#64748B",lineHeight:21,marginTop:8},input:{backgroundColor:"#fff",borderWidth:1,borderColor:"#E2E8F0",borderRadius:12,padding:14,marginBottom:10},area:{minHeight:110,textAlignVertical:"top"},select:{backgroundColor:"#fff",borderWidth:1,borderColor:"#E2E8F0",borderRadius:12,padding:14,marginBottom:10,flexDirection:"row",justifyContent:"space-between"},value:{fontWeight:"700"},placeholder:{color:"#94A3B8"},row:{flexDirection:"row",gap:10},half:{flex:1,backgroundColor:"#fff",borderWidth:1,borderColor:"#E2E8F0",borderRadius:12,padding:14,marginBottom:10},choice:{flex:1,padding:14,borderWidth:1,borderColor:"#E2E8F0",borderRadius:12,alignItems:"center",backgroundColor:"#fff"},choiceActive:{backgroundColor:"#0F5132"},choiceText:{fontWeight:"800"},choiceTextActive:{fontWeight:"800",color:"#fff"},button:{backgroundColor:"#0F5132",borderRadius:13,padding:16,alignItems:"center",marginTop:16},buttonText:{color:"#fff",fontWeight:"900"},error:{backgroundColor:"#FEE2E2",color:"#991B1B",padding:12,borderRadius:10,marginTop:12},modal:{flex:1,backgroundColor:"rgba(0,0,0,.35)",justifyContent:"flex-end"},sheet:{backgroundColor:"#fff",maxHeight:"85%",borderTopLeftRadius:20,borderTopRightRadius:20,padding:18},option:{padding:14,borderBottomWidth:1,borderBottomColor:"#F1F5F9",flexDirection:"row",justifyContent:"space-between"},muted:{color:"#64748B",fontSize:12},close:{padding:15,alignItems:"center",borderWidth:1,borderColor:"#E2E8F0",borderRadius:12,marginTop:10}});
