const API=process.env.NEXT_PUBLIC_API_URL??"http://localhost:4000/api/v1";let refreshPromise:Promise<any>|null=null;
export function apiUrl(path:string){return API+(path.startsWith("/")?path:"/"+path)}
async function parse<T>(r:Response){const text=await r.text();let data:any;try{data=text?JSON.parse(text):null}catch{data=text}if(!r.ok)throw Object.assign(new Error(data?.message||data?.error||("API "+r.status)),{status:r.status,data});return data as T}
async function request<T>(path:string,init:RequestInit,headers:Record<string,string>){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),15000);try{return await parse<T>(await fetch(apiUrl(path),{...init,headers,cache:"no-store",signal:init.signal??controller.signal}))}catch(e:any){if(e?.name==="AbortError")throw new Error("Request timed out. Check your connection and try again.");throw e}finally{clearTimeout(timer)}}
export async function api<T>(path:string,init:RequestInit={}){return request<T>(path,init,{"content-type":"application/json",...(init.headers as Record<string,string>||{})})}
async function refreshSession(){if(typeof window==="undefined")return null;if(refreshPromise)return refreshPromise;const refresh=localStorage.getItem("imizi_refresh");if(!refresh)return null;refreshPromise=api<any>("/auth/refresh",{method:"POST",body:JSON.stringify({refreshToken:refresh})}).then(next=>{localStorage.setItem("imizi_token",next.accessToken);localStorage.setItem("imizi_refresh",next.refreshToken);localStorage.setItem("imizi_user",JSON.stringify(next.user));return next.accessToken}).catch(()=>null).finally(()=>{refreshPromise=null});return refreshPromise}
export async function authApi<T>(path:string,init:RequestInit={},retry=true){if(typeof window==="undefined")throw new Error("Browser authentication required");let token=localStorage.getItem("imizi_token");const headers:Record<string,string>={...(init.headers as Record<string,string>||{}), "content-type":"application/json",...(token?{authorization:"Bearer "+token}:{})};try{return await request<T>(path,init,headers)}catch(e:any){if(e.status===401&&retry){const next=await refreshSession();if(next)return authApi<T>(path,init,false)}if(e.status===401){localStorage.removeItem("imizi_token");localStorage.removeItem("imizi_refresh");localStorage.removeItem("imizi_user")}throw e}}
export function formatRwf(n:number){return new Intl.NumberFormat("en-RW",{style:"currency",currency:"RWF",maximumFractionDigits:0}).format(Number(n||0))}
export function shortDate(v:string){return v?new Intl.DateTimeFormat("en-RW",{dateStyle:"medium"}).format(new Date(v)):"—"}
