"use client";
import{useEffect,useState}from"react";import{authApi}from"../../lib/api";
export default function Messages(){
 const[conversations,setConversations]=useState<any[]>([]),[active,setActive]=useState<any>(),[body,setBody]=useState(""),[err,setErr]=useState(""),[sending,setSending]=useState(false);
 async function load(){try{setConversations(await authApi<any[]>("/messages/conversations"))}catch(e:any){setErr(e.message)}}
 useEffect(()=>{void load();const t=setInterval(()=>void load(),5000);return()=>clearInterval(t)},[]);
 async function open(id:string){try{const c=await authApi<any>("/messages/conversations/"+id);setActive(c);await authApi("/messages/"+id+"/read",{method:"POST"})}catch(e:any){setErr(e.message)}}
 async function send(){if(!active||!body.trim()||sending)return;setSending(true);setErr("");try{await authApi("/messages",{method:"POST",body:JSON.stringify({conversationId:active.id,body:body.trim()})});setBody("");await open(active.id);await load()}catch(e:any){setErr(e.message)}finally{setSending(false)}}
 return <main className="wrap section"><div className="eyebrow">Live transaction messaging</div><h1>Inbox</h1><p className="muted">Conversations stay linked to the property, booking or offer that created them. The page refreshes conversation summaries while open.</p>{err&&<div className="notice error">{err}</div>}
 <div className="layout"><div className="panel"><div className="sectionLabel"><b>Conversations</b><span className="muted">{conversations.length}</span></div><div className="list">{conversations.map(c=><button className="row" style={{textAlign:"left",width:"100%"}} key={c.id} onClick={()=>void open(c.id)}><span><b>{c.title||c.otherUserName||"Conversation"}</b><br/><small className="muted">{c.lastMessage||"Open conversation"}</small></span><span>→</span></button>)}</div>{!conversations.length&&<div className="empty">No conversations returned by the API.</div>}</div>
 <div className="panel" style={{minHeight:520,display:"flex",flexDirection:"column"}}>{active?<><div><div className="eyebrow">Conversation</div><h2 style={{fontSize:24}}>{active.title||"Property conversation"}</h2><p className="muted">Property: {active.propertyId||"—"} · Booking: {active.bookingId||"—"}</p></div><div style={{flex:1,overflowY:"auto"}}>{(active.messages||[]).map((m:any)=><div className="row" key={m.id} style={{marginTop:10}}><span>{m.body}</span><small className="muted">{m.senderId===active.userId?"You":"Participant"} · {new Date(m.createdAt).toLocaleString()}</small></div>)}</div><div className="actions" style={{marginTop:14}}><input className="field" value={body} onChange={e=>setBody(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")void send()}} placeholder="Write a message…"/><button className="btn" disabled={sending||!body.trim()} onClick={()=>void send()}>{sending?"Sending…":"Send →"}</button></div></>:<div className="empty">Select a conversation to load its persisted message history.</div>}</div></div></main>;
}