"use client";
import { useEffect,useState } from "react";import { authApi } from "../../lib/api";
export default function Messages(){
 const[conversations,setConversations]=useState<any[]>([]);const[active,setActive]=useState<any>();const[body,setBody]=useState("");const[err,setErr]=useState("");
 async function load(){try{setConversations(await authApi<any[]>("/messages/conversations"))}catch(e:any){setErr(e.message)}}
 useEffect(()=>{void load()},[]);
 async function open(id:string){try{setActive(await authApi<any>("/messages/conversations/"+id));await authApi("/messages/"+id+"/read",{method:"POST"})}catch(e:any){setErr(e.message)}}
 async function send(){if(!active||!body.trim())return;try{await authApi("/messages",{method:"POST",body:JSON.stringify({conversationId:active.id,body:body.trim()})});setBody("");await open(active.id)}catch(e:any){setErr(e.message)}}
 return <main className="wrap section"><div className="eyebrow">Realtime communication</div><h1>Inbox</h1><p className="muted">Property conversations and transaction context in one place.</p>{err&&<div className="notice error">{err}</div>}
 <div className="layout"><div className="panel"><div className="sectionLabel"><b>Conversations</b><span className="muted">{conversations.length}</span></div><div className="list">{conversations.map(c=><button className="row" style={{textAlign:"left",width:"100%"}} key={c.id} onClick={()=>void open(c.id)}><span><b>{c.title||c.otherUserName||c.id}</b><br/><small className="muted">{c.lastMessage||"Open conversation"}</small></span><span>→</span></button>)}</div>{!conversations.length&&<div className="empty">No conversations returned by the API.</div>}</div>
 <div className="panel" style={{minHeight:520,display:"flex",flexDirection:"column"}}><div><div className="eyebrow">Conversation</div><h2 style={{fontSize:24}}>{active?.title||"Select a conversation"}</h2></div><div style={{flex:1}}>{(active?.messages||[]).map((m:any)=><div className="row" key={m.id} style={{marginTop:10}}><span>{m.body}</span><small className="muted">{m.senderId===active.userId?"You":"Them"}</small></div>)}</div>{active&&<div className="actions" style={{marginTop:14}}><input className="field" value={body} onChange={e=>setBody(e.target.value)} placeholder="Write a message…"/><button className="btn" onClick={()=>void send()}>Send →</button></div>}</div></div></main>;
}